### PR TITLE
Fixes JENKINS-69448

### PR DESCRIPTION
**Pull request by ericcitaire**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Looks good to me! Just need to manually confirm it works for both timer and non-timer jobs. But otherwise it looks like a perfect pull-request. Thanks a ton for including a unit test @ericcitaire !

**Review by kinow — APPROVED** [review]
Running locally, with JVM 11, using `mvn install` followed by `mvn hpi:run`. Brand new `work` directory.

Used the script snippet from the JIRA issue. Manual trigger:

image

image

Cloned the job, setting a timer scheduled for the next minute. Result after waiting a few seconds.

image

Thanks @ericcitaire !

**Comment by ericcitaire** [comment]
Thanks @kinow for merging these changes. Do you plan to release it anytime soon ? We really need this fix.

**Comment by kinow** [comment]
> Thanks @kinow for merging these changes. Do you plan to release it anytime soon ? We really need this fix.

Can't see a reason for not releasing it right now. I'm on my laptop with the Maven settings. It should be on the Update Center in the next hours (assuming there's no issue with the release).

**Comment by kinow** [comment]
2.6.4 is released! :tada:

**Pull request merged**
