### PR TITLE
[JENKINS-61068] set correct value on parambuild page

### PR DESCRIPTION
**Pull request by agabrys**
getDefaultParameterValue is used to get value on parambuild and buildWithParameters urls (trigger build). Those pages use text boxes to represent Active Choices parameters.

The method should respect users configuration and return values with ":selected" suffix. If no value contains the suffix, it should return the first element (backward compatibility).

### CODE REVIEW

**Comment by agabrys** [comment]
If you need more details - let me know. I described how the feature works in the [JENKINS-61068](https://issues.jenkins-ci.org/browse/JENKINS-61068) ticket.

**Comment by agabrys** [comment]
I'm aware of it and I ignored it. Why? The method which I introduced is used only on `parambuild` and `buildWithParameters`. These both pages display the parameter as a simple text box. It means that even if a job administrator configured something as a radio button, any user is still able to type `value1,value2` and get two values instead of one. Second thing is that the change returns a default value(s). If the job administrator configured input parameter as a radio button and marked two values as `:selected`, then I think we shouldn't care about it. On main page the second value will be marked as default and on the `parambuild` \ `buildWithParameters` both. But the problem is easy to fix by the job owner (don't configure two default values for the radio button).

**Comment by imoutsatsos** [comment]
I think we can merge this. I think @agabrys has given a rather good argument. If we can have an experimental build before the final release, I would love to give it a try. Thanks @agabrys  and @kinow  for this!!

**Comment by kinow** [comment]
Roger that @imoutsatsos . Merging tonight, then prepare an hpi and attach to the issue and CC you there. We can postpone the release for a few days/weeks to give you and others time to test it too :+1:  Thanks and thanks @agabrys too!

**Comment by kinow** [comment]
Hi @agabrys just waiting for https://issues.jenkins-ci.org/browse/JENKINS-61751 to be tested/merged too, then planning a release by the end of this month :+1:

**Pull request merged**
