### PR TITLE
Patch to solve JENKINS-49260

### PR DESCRIPTION
**Pull request by sebcworks**
Retrieve project using full name instead of only name to take nested folders into account.

See issue JENKINS-49260 (https://issues.jenkins-ci.org/browse/JENKINS-49260) to have more information about the problem.

A test was added, it fails if you comment out the fullname set, using only project "name". I wrote the test based on previous issues-related tests.

### CODE REVIEW

**Comment by kinow** [comment]
@sebcworks thanks a lot for your pull request. Code looks good, and big thanks for including a unit test!

@imoutsatsos FYI, merging it, and will cut a release next weekend. Minor change, but you might want to check if it will affect you :+1:

**Comment by sebcworks** [comment]
Thanks for taking it into account that quick!

**Comment by imoutsatsos** [comment]
Thanks @sebcworks  and @kinow ! I will be doing some testing returning to the office after a short vacation. Jusy wondering whether this patch affects/resolves https://issues.jenkins-ci.org/browse/JENKINS-51296 ?

**Comment by kinow** [comment]
🎉 and there comes another great pull request @sebcworks ! Thanks!

@imoutsatsos I'll attach to JENKINS-51296 a hpi plugin binary with this pull request, and #20 as well, so that you can test it 👍 

@sebcworks , 👏 👏 👏 :-)

**Pull request merged**
