### PR TITLE
Fixes JENKINS-66703

### PR DESCRIPTION
**Pull request by ericcitaire**
See [JENKINS-66703](https://issues.jenkins.io/browse/JENKINS-66703) for details.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ericcitaire** [comment]
> Would be nice a unit test but we can discuss that later.

This a Javascript error, I have no idea how to test this with Jenkins testing tools.

> I couldn't reproduce it on `master`.
> 
> Could it be that there is some plug-in, or maybe browser extension causing the issue?

I'm able to reproduce it by :
* setting `jenkins.version=2.277.4` in the `pom.xml` line 39
* running `mvn hpi:run`
* creating the job with the given configuration (see full configuration in JIRA)
* type some random text in the filter field
* looking at the Javascript console

Reproduced with :
* Chrome 96.0.4664.93 with no extension
* Firefox 78.7.1esr with no extension

**Comment by kinow** [comment]
Almost done with the TypeScript port at #57 , before merging that, I will try to reproduce this issue and if successful at that, will merge this one, then rebase that PR :+1: .

**Comment by ericcitaire** [comment]
> Almost done with the TypeScript port at #57 , before merging that, I will try to reproduce this issue and if successful at that, will merge this one, then rebase that PR 👍 .

Hey @kinow. #57 didn't change in 6 months and [JENKINS-66703](https://issues.jenkins.io/browse/JENKINS-66703) is almost 1 year old. We really need this bug to be fixed ! Please help !! Thanks in advance.

**Comment by ericcitaire** [comment]
Actually, this seems to be fixed in 2bc81150, but unreleased. We just need it to be released and at least 2 related issues could be closed.

**Comment by kinow** [comment]
> Actually, this seems to be fixed in [2bc8115](https://github.com/jenkinsci/active-choices-plugin/commit/2bc81150c0e102fc84741eb5c86e6251fb38ec24) (hence the conflict), but unreleased. We just need it to be released and at least 2 related issues could be closed.

Sorry @ericcitaire , I got side-tracked by $job & life, and other projects. Haven't had a chance to finish the port to TS (or JS improvement).

I've released what we have. Could you help testing this version and update the issues/PR's (feel free to ping me if you don't have permission to update the issue :+1: ). cc @imoutsatsos 

Thanks !!!
-Bruno

**Comment by ericcitaire** [comment]
Was fixed by https://github.com/jenkinsci/active-choices-plugin/commit/2bc81150c0e102fc84741eb5c86e6251fb38ec24

**Pull request closed without merging**
