### PR TITLE
Enhancement : a scriptler can access to Project

### PR DESCRIPTION
**Pull request by perfhector**
using def project=binding.variables.get('jenkinsProject')

### CODE REVIEW

**Comment by perfhector** [comment]
Oh, this does not inject a 'jenkinsProjet' when the build is triggered :(
That's disappointing

**Comment by perfhector** [comment]
Now even when a build is trigerred, "jenkinsProject" is exposed.
Please note that i use a JenkinsUtil class extract from the dynamicparameter plugin, under apache 2 licence. I've modified the file, but i've keeped the header for Apache Licence.
Please let me know.
Regards,
"perf'Hector"

**Comment by kinow** [comment]
Hi @perfhector !

You closed the pull request. Would you still need this feature? We can file an issue in issues.jenkins-ci.org to discuss different options. I haven't had time to work on this, but if you need some feature, I can probably help in my next development cycle for the plug-in :-)
Cheers
B

**Comment by perfhector** [comment]
Hi.
Grrrrr
Clicking on the "close" button, because i thought i had finished my
enhancement was not a good idea.
Oh course, i still need my feature,
I hadn't realize "close" would mean "cancel" for github.

It would be perfect if i could merge code with your..! So i'll push again
my pull request.

Thank you !

"Perfhector"



2015-08-29 6:13 GMT+02:00 Bruno P. Kinoshita <notifications@github.com>:

**Pull request closed without merging**
