### PR TITLE
[JENKINS-66411] Add a checkbox to enable/disable sandbox of Scriptler scripts, remove duplicated Scriptler code

### PR DESCRIPTION
**Pull request by kinow**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mtughan** [comment]
@kinow, this PR broke the use of Active Choice parameters in pipelines, as the DSL required has changed. In fact, the pipeline example in README.md still uses the old syntax and will **not** work with version 2.6.0.

Specifically, the DSL previously used the parameters `scriptlerScriptId` and `parameters` to the `ScriptlerScript` class. Now that it takes a `ScriptlerBuilder`, the DSL needs to be modified to construct and pass a `ScriptlerBuilder` instance as `scriptlerScriptId` and `parameters` do not have `@DataBoundSetter`-annotated setters to accept values from the DSL.

This isn't mentioned in the release notes and we only stumbled across this when pipelines that used this DSL suddenly stopped showing parameters from Scriptler scripts when attempting to build them with parameters.

**Comment by kinow** [comment]
@mtughan sorry, I didn't think about looking at the `README.md` examples nor at the DSL used by pipelines. If you have worked out what needs to be fixed and could send a pull request that would be great (to either/both examples and changelog/release notes). Thanks!

**Comment by mtughan** [comment]
@kinow, I think I should have a PR shortly that will fix it. I've tested it locally and it seems to work fine with pipelines, but I want to write a unit test first to make sure that this works and will ensure it continues to work. I hope to have that done in a few hours.

**Comment by kinow** [comment]
> @kinow, I think I should have a PR shortly that will fix it. I've tested it locally and it seems to work fine with pipelines, but I want to write a unit test first to make sure that this works and will ensure it continues to work. I hope to have that done in a few hours.

That's excellent @mtughan ! @imoutsatsos warned me about a regression in the latest version too, and I've been planning to start a development cycle for a new release soon, so if you have other issues that you'd like to see fixed, just let me know and I'll try to prioritize too.

Thanks!

**Comment by mtughan** [comment]
@kinow, #59 should resolve this. Please review when you're available.

**Comment by kinow** [comment]
Merged, and changelog updated with credit and thanks! Thank you @mtughan :+1:

**Pull request merged**
