### PR TITLE
Update AbstractScriptableParameter.java

### PR DESCRIPTION
**Pull request by jhammell**
if-else logic in latest version is causing Active Choice parameter to not populate

### CODE REVIEW

**Comment by kinow** [comment]
Thanks for the PR @jhammell. How easy is it to reproduce the issue? Just so I can test it from master, and then after switching to your branch to understand what's wrong, please :)

**Comment by jhammell** [comment]
Hi @kinow,  I work for a large enterprise Cloudbees Jenkins shop, and discovered the this after a mass upgrade of plugins.  It was not quite a 'heisenbug', but odd how it only affected one of the masters.  I have submitted another pull request to not test for 'project =! null' when trying to locate the UUID and fall into the else statement if projectFullName or projectName can't be found.  If this causes an issue with the business cases you have, you can alway add a try/catch/throw around the block.

**Comment by jhammell** [comment]
Hi @kinow ... Unfortunately I don't have the ability to follow my code changes at runtime.  I think my reading what I've done that maybe you can add the change.  When I fixed it @work I built w/o running unit tests (it's not an option there).  If you have anymore questions feel free to shoot them my way.  I'd also like to grab a snapshot build before the next release is cut so I can test it to make sure the issue is corrected -- Thanks, Jackie

**Comment by jhammell** [comment]
PS...I don't have access to do anything on GitHub from my off

**Comment by kinow** [comment]
Hi Jackie

Itight be better creating an issue on Jira. There, others may chime in and report what happened in their case.

If you have a simple way to reproduce the bug that would be helpful too.

As for early versions, I normally upload .hpi files to the Jira issues too.

Bruno

**Comment by ZachDZimmerman** [comment]
@jhammell we can open a JIRA ticket on our side if you want to send me the entire scope of what you are looking to do with this fix.

**Pull request closed without merging**
