### PR TITLE
Additional fix for: JENKINS-65096

### PR DESCRIPTION
**Pull request by szjozsef**
- additional changes to https://github.com/jenkinsci/active-choices-plugin/pull/45
- FIX for some tasks the html already contains the element list, in that case the javascript filled the elements under the first element, practically creating them as additional elements. I still does not understand why for some similar tasks there are pre-generated values for others just error values and then the right values will get filled via javascript.
- added a few more if's for backward compatibility (was not tested with jenkins < 2.277.1)
- added the class "tr" to tr like div elements to match the pre-filled elements (from jelly templates), not all element type was tested

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did additional if conditions to separate for the TABLE and DIV based rendering, add 'tr' style to the java-script generated elements
- [x] Link to relevant issues in GitHub or Jira https://issues.jenkins.io/browse/JENKINS-65096
- [x] Link to relevant pull requests, esp. upstream and downstream changes addition to: https://github.com/jenkinsci/active-choices-plugin/pull/45
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by szjozsef** [comment]
@oleg-nenashev @kinow Can you please review ? and if you consider merge it.

**Review by oleg-nenashev — APPROVED** [review]
Looks reasonable though I have not tested it locally

**Comment by kinow** [comment]
On my todo list. Having a few meetings this week, and something with a deadline.

Will try to review it Friday/weekend or sooner if possible 👍

Thank you for the PR @szjozsef !

**Review by kinow — COMMENTED** [review]
I wonder if it wouldn't be easier to split the initial if

`if (parameterElement.children.length > 0 && (parameterElement.children[0].tagName === 'TABLE' || parameterElement.children[0].tagName === 'DIV')) {`

And have two branches. One for the old behaviour with table, and another with the div.

The old one would be the same as before. While the new one would have these changes for DIV based layout.

Then eventually we would be able to just delete the other if branch completely, instead of having to chase which if statements must go away.

**Comment by szjozsef** [comment]
with his variant the variable divBased is not needed anymore

**Review by kinow — COMMENTED** [review]
Thank you @szjozsef !!! :tada: 

Looks much better. Now the only challenge will be to test it with divs and with tables. Will need some strong :coffee: and plenty of :watch: . Promise I will try to finish reviewing this week. Once I've finished testing it, will merge & cut a release :+1: 

Bruno

**Comment by kinow** [comment]
@imoutsatsos we really need to talk again about that test-battery idea we had in our last session. Create the scenarios necessary, and translate into JS tests.

@szjozsef my plan is to delete this code I wrote ages ago, and replace by either a library for reactivity or vue/react (probably vue as I'm using it at the moment, and we can start the vue-app inside any page). Also use mocha/chai or jest for unit testing, and cypress for the e2e tests. Plus the normal Jenkins tests.

Probably after a release with no major issues, to leave the code to stabilize and reduce risks/changes for users :+1: (probably Q4 this year).

**Comment by imoutsatsos** [comment]
@kinow thank you. I will schedule another v-meeting soon!

**Review by kinow — COMMENTED** [review]
Managed to find time today to sync my local copy of this branch, review the code with the IDE (looks good, nothing appears to be missing that I can tell), and download Jenkins 2.204.1 and 2.277.1. I will use these two versions to compare a job with

- groovy script
- several cascading parameters of types
  - input
  - select
  - select multiline
  - radio
  - check box
  - formatted html
  - formatted html hidden

Have already packaged a `.hpi` for this branch. So now I'll start tomorrow probably with 2.204 first :+1:

**Comment by kinow** [comment]
Tested Jenkins ver. 2.204.1, worked with no issues.

- `mkdir jenkins-2.204.1`
- `export JENKINS_HOME=${PWD}/jenkins-2.204.1`
- `java -jar jenkins-2.204.1.war`
- Installed recommended plug-ins
- Manually installed hpi from this PR
- Tested with the attached `config.xml`
- Screenshot showing the rendered parameters displayed correctly (except `h` which is hidden, but confirmed it's there)
- 
Screen Shot 2021-03-25 at 11 45 41-fullpage

[config.xml-2.204.1.zip](https://github.com/jenkinsci/active-choices-plugin/files/6200899/config.xml-2.204.1.zip)

**Comment by kinow** [comment]
Tested the same with 2.277.1. Only one difference, which was reported in JENKINS-65173, the hidden parameter is displayed, due to this line: https://github.com/jenkinsci/active-choices-plugin/blob/5d95ceed25e65110d1d1bcf3ed6b1650d691cee5/src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly#L77

Screen Shot 2021-03-25 at 12 13 37-fullpage

**Review by kinow — CHANGES_REQUESTED** [review]
~Could you apply this diff too, please @szjozsef ?~

```diff
diff --git a/src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly b/src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
index 6a21add..4010f6a 100644
--- a/src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
+++ b/src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
@@ -75,6 +75,11 @@
     // if the parameter class has been set to hidden, then we hide it now
     if (parentDiv.get(0).getAttribute('class') == 'hidden_uno_choice_parameter') {
       var parentTbody = jQuery(parentDiv.get(0)).parents('tbody');
+      // FIXME: temporary fix to support both TABLE and DIV in the Jenkins UI
+      //        remove after most users have migrated to newer versions with DIVs
+      if (!parentTbody || parentTbody.length === 0) {
+        parentTbody = jQuery(parentDiv.get(0)).parents('div > div.tr');
+      }
       if (parentTbody &amp;&amp; parentTbody.length > 0) {
         jQuery(parentTbody.get(0)).attr('style', 'visibility:hidden;position:absolute;');
       }
```

That fixes the JENKINS-65173 issue, allowing table/div's to act the same with regards to hidden parameters.

No other changes required IMO, should be ready to merge/release after that :+1:

**Comment by kinow** [comment]
Oh, d'oh, I can apply the diff during the merge. LGTM. Releasing in a few minutes/hours too.

**Pull request merged**
