### PR TITLE
JENKINS-39665 Set height for more than 10 choices

### PR DESCRIPTION
**Pull request by stankolubomir**

### CODE REVIEW

**Comment by kinow** [comment]
No errors in my JS console, but apparently it didn't change much from the results from that last pull request.

image

I am testing with a simple active parameter that has a script like `return 1..999`

**Comment by stankolubomir** [comment]
I don't understand. On my local machine it works with your script. Check screenshot.
jenkins_choices

**Comment by kinow** [comment]
I also don't understand. Tested on latest version of Firefox and Chrome on a Ubuntu LTS (18.04 bionic) computer.

Deleted my branch and checked out your pull request again. Same result. Checked commits logs

```bash
$ git log -n 1 --patch
commit a8422524b1e13f1802c204148acc88a95a0c93d0 (HEAD -> pr-22)
Author: Lubomir Stanko <lubomir.stanko@newsandmedia.sk>
Date:   Wed Oct 3 19:57:51 2018 +0200

    JENKINS-39665 Set height for more than 10 choices

diff --git a/src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly b/src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly
index 9fcd825..412452f 100644
--- a/src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly
+++ b/src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly
@@ -51,8 +51,11 @@
           else {
               height = maxCount * 25.5;
           }
-          height = Math.floor(height);
-          document.getElementById("ecp_${it.randomName}").style.height = height + "px";
+^M
+          if (${it.visibleItemCount} > 10) {^M
+              height = Math.floor(height);^M
+              document.getElementById("ecp_${it.randomName}").style.height = height + "px"; ^M
+          }^M
       };
 
       f();
diff --git a/src/main/resources/org/biouno/unochoice/common/radioContent.jelly b/src/main/resources/org/biouno/unochoice/common/radioContent.jelly
index c83c84f..14d4a34 100644
--- a/src/main/resources/org/biouno/unochoice/common/radioContent.jelly
+++ b/src/main/resources/org/biouno/unochoice/common/radioContent.jelly
@@ -54,8 +54,11 @@
           else {
               height = maxCount * 25.5;
           }
-          height = Math.floor(height);
-          document.getElementById("ecp_${it.randomName}").style.height = height + "px";
+^M
+          if (${it.visibleItemCount} > 10) {^M
+              height = Math.floor(height);^M
+              document.getElementById("ecp_${it.randomName}").style.height = height + "px";^M
+          }^M
       };
 
       f();
diff --git a/src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js b/src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js
index 6b0cea3..b9c3fb2 100644
--- a/src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js
+++ b/src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js
@@ -352,7 +352,9 @@ var UnoChoice = UnoChoice || (function($) {
                     /*
                      * This height is equivalent to setting the number of rows displayed in a select/multiple
                      */
-                    parameterElement.style.height = '' + (23 * (newValues.length > 10 ? 10 : newValues.length)) + 'px';
+                    if (newValues.length > 10) {
+                        parameterElement.style.height = '' + (23 * (newValues.length > 10 ? 10 : newValues.length)) + 'px';
+                    }
                 } // if (oldSel.children.length > 0 && oldSel.children[0].tagName == 'TABLE')
             } // if (oldSel.tagName == 'SELECT') { // else if (oldSel.tagName == 'DIV') {
         });
```

Tried saving the job, and reload (force reload) in both browsers, with no luck.

Stopped Jenkins (running in maven) and just did a `git checkout master`, started Jenkins again, and reloaded in the browsers, and now the existing behaviour was correctly displayed.

I think I'm testing your code, but for some reason it appears it has no effect on my current environment? Might be able to get another computer to test it later this/next week.

**Comment by stankolubomir** [comment]
I'm testing this with completely fresh jenkins installation started in docker. I'm using [jenkins/jenkins](https://hub.docker.com/r/jenkins/jenkins) docker repository. Maybe you could check it this way. But it is weird it is not working on your current jenkins installation.

**Comment by kinow** [comment]
Weird indeed, and it seems to be either something with my environment, or something that I am doing wrong. Reviewing your code, it looks great and ready to be merged. Have a few more minutes now while I wait a job to finish, so will give it another try.

**Comment by kinow** [comment]
Got distracted by other tasks, so will have a short time to test it now :cry: 

Here's what I am doing... still insisting on testing on my environment, as I tested other features this way, and would like to understand if there's anything that I need to change when testing pull requests.

So I did

```bash
$ vim src/main/resources/org/biouno/unochoice/common/radioContent.jelly
```

Then went straight to line `57`. And changed a bit your code to always pass as `true`.

```javascript
          if (true || ${it.visibleItemCount} > 10) {
              height = Math.floor(height);
              document.getElementById("ecp_${it.randomName}").style.height = height + "px";
          }
```

And then it worked immediately when I reloaded the browser

image

Which means that `${it.visibleItemCount}` is part of the mystery...

**Comment by kinow** [comment]
I didn't have time to investigate much more @stankolubomir , but I suspect my example `1..999` returns an `IntRange`. That `visibleItemCount` variable is defined by `length` in some parts of the Java code... so might be that we found another bug.

Going to have to spend some time on another project, and it's almost Friday/Weekend for me, so unless I find some spare time to review it today, it will slip to the next week. But feel free to comment here in case you found another solution, have any comments, or if I take too long to reply.

Cheers
Bruno

**Comment by stankolubomir** [comment]
@kinow I've probably fixed the behavior of setting height. I've set "230px" for more than 10 choices as it would have been calculated anyway in [unochoice.js](https://github.com/jenkinsci/active-choices-plugin/pull/22/commits/111ba6a8e35c6c216a25bac017a955dfe84b4954#diff-23c5abddb36bd169be72750980c100a3). And I've set "auto" height if there is 10 or less choices. I've also reverted my changes in [checkboxContent.jelly](https://github.com/jenkinsci/active-choices-plugin/pull/22/commits/111ba6a8e35c6c216a25bac017a955dfe84b4954#diff-a5795f4636cbaa8f2ddb5486a750cf16) and [radioContent.jelly](https://github.com/jenkinsci/active-choices-plugin/pull/22/commits/111ba6a8e35c6c216a25bac017a955dfe84b4954#diff-86a7233b9fd94392803d66367f6ec8ea) for better performance in the browser.
I've also realized that the code might be prettier, so I've adjusted [unochoice.js](https://github.com/jenkinsci/active-choices-plugin/pull/22/commits/8d1ac5fec65be0b89fb4c631babd4ee972a0b5bd#diff-23c5abddb36bd169be72750980c100a3) after my changes.

**Comment by kinow** [comment]
Looks promising! And also way easier to read :clap: 

I tested with 11, 10 and 5 elements. The scrollbar was displayed for all these options. Any idea if there's any further optimization needed? I thought the `auto` would do the trick in the case of 5, and maybe 10 elements?

image

**Comment by stankolubomir** [comment]
I've tried and tested it again. I can not reproduce your behavior in any way.
It looks like your browser is reading just checkboxContent.jelly and radioContent.jelly and not unochoice.js.
My browser first reads checkboxContent.jelly and radioContent.jelly but at the end of the page loading it reads unochoice.js and sets up correct height according to number of choices.
Could you tell me please your browser with the version? And also Jenkins version. I'll try to reproduce your environment on my side.

**Comment by kinow** [comment]
Sorry for the delay @stankolubomir . I was actually waiting till I had time to quickly test it at work, where I have a very similar Ubuntu environment, but haven't used active choices there in ages.

Just finished testing it, here are some screen shots, on Firefox running on Ubuntu LTS (tested Chrome, and worked as well)

**Comment by kinow** [comment]
Merged, thanks @stankolubomir !!!

**Pull request merged**
