### PR TITLE
[JENKINS-6509] - Fix Active Choice Reactive Parameter rendering with Jenkins 2.277.1

### PR DESCRIPTION
**Pull request by szjozsef**
a possible fix for: https://issues.jenkins.io/browse/JENKINS-65096

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did: Extended the if condition also to DIV tags in addition to TABLE tag
- [x] Link to relevant issues in GitHub or Jira: https://issues.jenkins.io/browse/JENKINS-65096
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
@kinow Hi, would it be possible to review and release it? AFAICT the regression is present in the recent LTS release

**Review by kinow — APPROVED** [review]

**Comment by kinow** [comment]
Hi @oleg-nenashev , sure thing.

@szjozsef thanks for your pull request. It looks harmless, and makes sense as we now have both div/table. We fixed in the stapler, but apparently didn't fix that in the JS code, good catch.

Hard to write a unit/functional test for that, and eventually we will have everyone using the div version. I'll merge, update the changelog, and cut a quick release now and update the issue.

Thanks!
Bruno

**Comment by kinow** [comment]
2.5.5 released :+1: thanks!

**Comment by oleg-nenashev** [comment]
Thank you!

**Pull request merged**
