### PR TITLE
[JENKINS-65813] Add @Symbol to support pipeline

### PR DESCRIPTION
**Pull request by kinow**
Supersedes #43 

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by kinow** [comment]
@mawinter69 I think you had a comment about the HTML help files too. Would you have a suggestion on how these files should look like?

**Comment by mawinter69** [comment]
> @mawinter69 I think you had a comment about the HTML help files too. Would you have a suggestion on how these files should look like?

Just put a help.html file next to the config.jelly of the parameters.

**Comment by kinow** [comment]
> > @mawinter69 I think you had a comment about the HTML help files too. Would you have a suggestion on how these files should look like?
> 
> Just put a help.html file next to the config.jelly of the parameters.

I thought you were suggesting improving the existing help files: https://github.com/jenkinsci/active-choices-plugin/tree/master/src/main/webapp

I will have a look to see if they are not being displayed. It worked in the past, but I haven't used it with newer versions.

**Comment by mawinter69** [comment]
The help is displayed, but what is missing is a general description of what the parameters are doing.
As an example look at the File Parameter. It has a help button right on top and explains how this parameter works.
image

Such help texts are missing for active choices and the only way to learn how they work is by visiting the plugin page.

**Comment by 0054** [comment]
Any news?
this will be a very useful feature

**Comment by kinow** [comment]
> Any news? this will be a very useful feature

Hi @0054 

Had forgotten about this PR, thanks for the bump :+1: . I'm checking out the `master` branch, running the tests to confirm it's OK, and will rebase this PR.

If all goes well I hope this can be merged in the next hour to be included in the next release.

**Comment by kinow** [comment]
Rebased, push-forced. Let's wait for CI.

**Comment by kinow** [comment]
CI is good. Now trying to add the help files @mawinter69 pointed out we are missing here.

**Comment by kinow** [comment]
@mawinter69 each parameter now has its own help file displayed next to its type/name.

image

image

I wrote some quick description for each parameter, but @imoutsatsos or someone else can improve it later if needed, so we don't block this PR based on that :+1: 

Thanks for the feedback!

**Comment by kinow** [comment]
Righto, last requirement now

>Ensure you have provided tests - that demonstrates feature works or fixes the issue

Let's see if I can find a way to test it now.

**Comment by kinow** [comment]
Test for the help files added. It is a Selenium test that was failing, complaining that it would click on an element in the footer instead of on the help icon. Tried using the predefined timeout but that didn't work. Then set the resolution to a wider screen and it solved (I guessed it was using some default smaller resolution, causing the elements to overlap).

Just missing some manual tests with pipelines, and maybe a test for that too.

**Comment by kinow** [comment]
I don't think it's easy to write a test for this. I had to install the `Pipeline`  plugin.

Screenshot from 2023-10-08 20-39-59

Then use the declarative generator to create a simple parameter.

Screen Shot 2023-10-08 at 20 55 16-fullpage

Pasted into a pipeline job

Screenshot from 2023-10-08 20-56-22

Then build it to produce an updated job, and build with parameters is shown.

Screenshot from 2023-10-08 20-57-28

I will push one more commit with the updated change log, then merge it. To be included with next release (in days/weeks, need to sort out my user+pass to Jenkins repositories).

**Comment by kinow** [comment]
> Does this PR still need a corresponding test with declarative pipeline? I'd be happy to help add one.

Hi @MattLud , that'd be great! In this PR I only added one for the help files, so covering the declarative pipeline would be excellent!

Thanks

**Pull request merged**
