### PR TITLE
[JENKINS-39665] Fixed unnecessary scrollbars on build with parameters screen

### PR DESCRIPTION
**Pull request by somejavadev**
I have added an element style to both the checkbox and radiobutton containers used on the [build with parameters] screen. I have also removed the Javascript which did calculations on the height of these containers as this is now unnecessary.

Pushing to the plug-in repository under the Jenkins organization as per @kinow

### CODE REVIEW

**Comment by somejavadev** [comment]
@kinow, seems like jenkins @ cloudbees is hanging. The build for this pull request (#105) was aborted after a timeout. I see the previous build (#104) threw a [ java.lang.OutOfMemoryError: PermGen space ] error which might be the cause of the slow running build.

**Comment by kinow** [comment]
Not a problem @somejavadev 

I normally check out pull requests locally and test them anyway. Will make sure the tests are all passing.

Reviewing right now :-)

**Comment by kinow** [comment]
All tests passing locally :+1: 

However, the changes to the user interface could cause some trouble.

The plug-in was created for life sciences, and it is common to have jobs with a long list of parameters (think like gene names, proteins, species, cells, etc). So having a list with hundreds or thousands of parameters is not really uncommon.

With that in mind, we added a limit to the number of elements displayed, and also added a filter element.

I tested the change locally, with two parameters, called radio and checkbox. The Groovy script used in both is the same: `return 1..1000`. Here's the screen shots, my browser is Firefox 49.0.2, on Ubuntu 16.04.2:

before

after

As you can see in the second image (after the change), for not having a scroll bar, the list goes on and on. Users would have to look for the filter element, and would probably start using the Find feature of browsers instead.

@somejavadev do you think the CSS element style alone would be something good to have? Would it work with the current JS code that was removed in the pull request?

**Comment by somejavadev** [comment]
Thanks for the reply. I have tested by only adding the style but it produces the same problem you have mentioned.  The user would need to scroll down using the browsers scrollbar for the length of all options. For me it's just a cosmetic thing when you have only 2 options or so and see the scrollbar. I will close this request and we leave it as is.

**Comment by kinow** [comment]
Thanks for updating the ticket @somejavadev 

Feel free to submit more pull requests/issues. Always happy and keen to review any contribution and provide feedback.

Cheers
Bruno

**Pull request closed without merging**
